
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/26ru/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.3.0 - arm64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/26ru/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.4.0 - arm64
...
